### ISSUE TITLE
Sync release issue from 1.1.0.1 for utci parameter

### ISSUE THREAD

**Issue by corentincarton** [ecmwf/pproc#10]
### What happened?

Chris found a small issue with the latest module (1.2.0.0). When computing the quantiles for the utci parameter, he got he following error:
```
pyfdb.pyfdb.FDBException: Error in function fdb_expand_request: UserError: UserError: Cannot match parameter 261001 request=retrieve,class=od,date=20240710,domain=g,expver=9001,stream=enfo,time=0,type=cf,area=e,levtype=sfc,step=1,param=261001, expanded=retrieve,class=od,date=20240710,domain=g,expver=9001,stream=enfo,time=0000,type=cf,area=e,levtype=sfc,step=1,param=261001
```
After a small investigation, it seems the bug started when we updated the stack for 1.1.0.1. I discussed with Emanuele and the issue can be solved by setting the following env variable `export METKIT_RAW_PARAM=1` but we should work with them to make sure this becomes the default behaviour. 

### What are the steps to reproduce the bug?

Run the following to reproduce the bug:
```
module load pproc/1.2.0.0
 
cat > config.yaml <<EOF
n_par_compute: 24
n_par_read: 24
num_members: 51
num_quantiles: 1
out_keys:
  expver: '0001'
params:
  utci:
    in: 261001
    in_keys:
      levtype: sfc
queue_size: 30
sources:
  fdb:
    ens:
    - area: e
      class: od
      date: 20240710
      domain: g
      expver: '9001'
      stream: enfo
      time: 0
      type: cf
    - area: e
      class: od
      date: 20240710
      domain: g
      expver: '9001'
      stream: enfo
      time: 0
      type: pf
windows:
- range:
  - 1
  - 90
  - 1
- range:
  - 93
  - 144
  - 3
- range:
  - 150
  - 240
  - 6

EOF
export FDB_HOME=/home/fdbdev
pproc-quantiles -c config.yaml --in-ens fdb:ens --out-quantiles utci.grib
```

### Version

1.1.0.1

### Platform (OS and architecture)

HPC
